replicaCount: 1

web:
  name: frontend-app
  image:
    repository: docker.apps.adriaanmolendijk.info/frontend-app
    tag: latest
    pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080

